version: '3.1'

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
    - local-data:/data/db

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    depends_on:
      - mongo

volumes:
  local-data:
    driver: "local"