name: Push and Upload

on:
  workflow_dispatch:

jobs:
  tests:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build JAR
        run: mvn clean install
      - name: Docker Hub Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: luliin/solo-project:latest
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: app.jar
          path: target/*.jar
